#!/bin/bash

#Two solutions, the first one is too complicated 

num=1
lsa=$( ls )
wcw=$( ls | wc -w )

until [[ "$num" -gt "$wcw" ]] ; do
     lsb=$( echo "$lsa" | cut -d$'\n' -f$num  )
     mv "$lsb" "name$num" #can add path berore second var or move without renaming by adding path and changing second var and name to first var

     (( num ++ ))
done

# a more efficient way of doing it would be:

n=1
for file in ./*; do
  mv "$file" "./name$n"
  ((n++))
done
